In [3]:
import numpy as np

t = np.eye(3)
t[:2, -1] = np.array([2, 0])

r = np.array(
    [
        [np.cos(np.deg2rad(15)),-np.sin(np.deg2rad(15)), 0],
        [np.sin(np.deg2rad(15)), np.sin(np.deg2rad(15)), 0],
        [0,0, 1]
    ]
)
r @ t

array([[ 0.96592583, -0.25881905,  1.93185165],
       [ 0.25881905,  0.25881905,  0.51763809],
       [ 0.        ,  0.        ,  1.        ]])

In [16]:
x_t = np.array([
    [-1, 1],
    [-1, 1],
    [1, 1]
])

x = np.array([
    [0, 1000],
    [0, 500],
    [1, 1]
])

s =  np.array([
    [2/1000, 0, -1],
    [0, 2/500, -1],
    [0, 0, 1]
])

display(np.linalg.inv(s))
x_t @ np.linalg.pinv(x)  # this works
#why can't I solve for s  with #(x_t @x.T) @ np.linalg.pinv(x @ x.T)?

array([[500.,   0., 500.],
       [  0., 250., 250.],
       [  0.,   0.,   1.]])

array([[ 1.60000000e-03,  8.00000000e-04, -1.00000000e+00],
       [ 1.60000000e-03,  8.00000000e-04, -1.00000000e+00],
       [-1.08420217e-19, -5.42101086e-20,  1.00000000e+00]])